---
title: "Ch1: Golem of Prague"
author: "Jesse Brunner"
format: 
  revealjs:
    embed-resources: true
---

## Statistical models as golems

-  Powerful & unyielding
-  Follow instructions with single-minded purpose
-  Only "know" what they are told to do

::: {.fragment .fade-up}
Cannot tell us what is "right" or "True"
:::

::: {.fragment .fade-up}
Cannot even tell us what is "OK to say" (_not_ police!)
:::

::: {.fragment .fade-up}
Golems are _tools_
:::

## Why can't golems _rule out_ or _falsify_ hypotheses?

1.  Hypotheses are not models^[golems only know how to deal with models]

-  One hypothesis might be represented by many model**s**

::: {.fragment .fade-in}
_Hypothesis_: pathogen transmission is shaped by variability in susceptibility

_Models_: $\beta I^p S^q$, $ks \ln\left(1+\frac{\beta I}{k}\right)$, $\frac{\beta S I}{c+S+I}$, ...
:::

## Why can't golems _rule out_ or _falsify_ hypotheses?

1.  Hypotheses are not models 

-  One hypothesis might be represented by many model**s**
-  One model might be consistent with many hypothese**s**

::: {.fragment .fade-in}
_All_ of those models might come from heterogeneity in susceptibility...

but also come from spatial or contact structure, etc.
:::


## Why can't golems _rule out_ or _falsify_ hypotheses?

1.  Hypotheses are not models
2.  Measurements matter
-  Observation error: _uncertainty in what we observe, biases, measurement error_
-  Hypotheses are continuous: _X is more/less important, not simply T/F_

::: {.fragment .fade-in}
How close is close/far enough?  
Any threshold or decision rule is arbitrary
:::



## Let's simulate some data {.smaller}

| Round | Heads | Coins flipped |
|-------|-------|---------------|
| 1     |       |               |
| 2     |       |               |
| 3     |       |               |
| 4     |       |               |
| 5     |       |               |
| 6     |       |               |
| 7     |       |               |
| 8     |       |               |
| 9     |       |               |
| 10    |       |               |
| 11    |       |               |
| 12    |       |               |
| 13    |       |               |
| 14    |       |               |
| 15    |       |               |
| 16    |       |               |
| 17    |       |               |
| 18    |       |               |
| 19    |       |               |
| 20    |       |               |


## Why can't golems _rule out_ or _falsify_ hypotheses?

1.  Hypotheses are not models
2.  Measurements matter
3.  We make inference as a group, by consensus, outside of routines

::: {.fragment .highlight-red} 
Science is not a series of statistical procedures!
::: 

:::  {.fragment .fade-in}
**We must be the captains of our own ships**
:::



## What do you want from your statistics?

:::: {.columns}

::: {.column width="40%"}
Understand **causation**?

-  Does $x \rightarrow y$?
-  Is $x_1$ more important than $x_2$?
-  What is the value of parameter $\beta$?
:::

::: {.column width="60%"}
**Predict** likely outcomes?

-  Which model is better at predicting new observations?
-  What can we expect in a new time or place?
:::

::::

::: {.fragment .highlight-red}
_These are not the same_
:::

## Different goals require different approaches

:::: {.columns}

::: {.column width="40%"}
Understand **causation**?

-  Experiments
-  Directed acyclic graphs
-  Path analysis

:::

::: {.column width="60%"}
**Predict** future outcomes?

-  Cross validation
-  Information criteria 
-  Sensitivity analysis
:::

::::

::: {.fragment .highlight-red}
Good prediction $\neq$ causation
:::

## You are the captain of your own ship

You must learn to 

* think carefully and skeptically (theory, DAGs, etc.)
* be specific about what you want to know (estimands)
* see the consequences of the assumptions you are making (simulations)
* understand and embrace uncertainty (distributions)
* dive into the weeds! (this class)

::: {.fragment .highlight-red}
Analysis is not an easy afterthought after the hard work of collecting the data... 
It is a core part of the whole process!
:::

 