---
title: "Your own data: simulating from your model"
author: "Jesse Brunner"
date: "`r Sys.Date()`"
format: 
  html:
    toc: true
    embed-resources: true
    code-fold: false
execute:
  include: true
---

# Overview
It is a truism that people don't learn statistics until they need to use them for their own purposes with their own data. While I am _certain_ most of your research questions involve statistical golems that are much more complex than we are ready to use (yet), I'm also sure we can carve out a simpler part of your (or your advisor's) research and data that might be amenable to analysis with the tools we have so far. We'll treat this as a jumping off point. 

Also, I'm here to help along the way, both to clarify the activity and help you think through your problem(s).

Here's what I would like you to do:

## 1. Sort out a simple question to ask of existing (or soon-to-be existing) data 
I'd like you to focus on a fairly simple relationship (e.g., a response to a simple predictor or two). It does not need to be a linear model, but it can be. (Think of the functional response example I provided as a reference.) Nothing too fancy, but make it meaningful and interesting to you. Most importantly, think about what you want to know from it! Are you interested in the overall effect of a predictor? Of a particular path? Sorting out the causal structure? Are you trying to make a predictive model? 

## 2. Write out the DAG or generative model
Think about what you expect to _cause_ what else. If there are multiple possible causal models, then draw them all. If you have a clear scientific model, draw or write that out. 

## 3. Simulate data given how you think things work
This is your chance to put some math behind your generative model. If you had a clear scientific model you may already have the math worked out. If not, think about the way you think your response should change with your predictor(s). In either case you'll also have to choose realistic-ish values of your predictors and you'll have to choose parameter values. This will undoubtedly involve some futzing with things until you are happy with the relationships and simulated data. 

## 4. Write out and fit the appropriate statistical model 
You made up the data and you thought about what it is you want to know from it (or more likely, real data), so now you have your chance to fit a model. We've done this a few times now, but since it is "real" it may feel different. Just keep it simple. 

## 5. Evaluate whatever it is you wanted to learn from your model
Depending on your goal, you may want to do something different. Perhaps it was seeing if you could recover the True value of some parameter. Perhaps it was seeing if you could distinguish between the True and alternative model. Or maybe you just needed to see how well your model could predict new observations. Whatever it is, do your best to use your fitted model and outside logic to do that thing. 